---
- name: 09.2-exercise-sudoers-template
  hosts: zeus,hades
  become: true
  tasks:
    - name: Read the vars in
      ansible.builtin.include_vars:
        file: users.yaml

    - name: Copy sudoers file
      ansible.builtin.template:
        src: sudoers_template.j2
        dest: /etc/sudoers.d/allow_apt_{{ item.name }}
        mode: "0400"
      when: item.can_update | bool
      loop: "{{ user }}"

    - name: Get all sudoers files
      find:
        path: /etc/sudoers.d/
        patterns: 'allow_apt*'
      register: found_items

    - name: Look at all sudoers files
      ansible.builtin.include_tasks: look_at_files.yaml
      loop: "{{ found_items.files }}"
