- name: 08-soultion-package-install
  hosts: zeus,hades
  become: true
  tasks:
    - name: Install zsh package
      ansible.builtin.package:
        name: zsh

    - name: Ensure bobs login shell is set to his favourite one
      ansible.builtin.user:
        name: bob
        shell: /bin/zsh
