- name: 09.1-solution-multiple-users
  hosts: all
  tasks:
    - name: Read the provided user file
      ansible.builtin.include_vars:
        file: ../09.1-exercise-multiple-users/users.yaml
        name: users

    - name: Ensure all the users are present
      ansible.builtin.user:
        name: "{{ item.name }}"
        comment: "{{ item.description }}"
        shell: "/bin/{{ item.favourite_shell }}"
        password: "{{ item.initial_password | password_hash('sha512') }}"
      become: true
      loop: "{{ users.people }}"
