---
- name: 09.2-solution-sudoers-template
  hosts: all
  tasks:
    - name: Read the provided user file
      ansible.builtin.include_vars:
        file: ../06-exercise-sudoers-template/users.yaml
        name: user

    - name: Output user
      debug:
        var: user.user

    - name: Template the sudoer file
      ansible.builtin.template:
        src: "{{ playbook_dir }}/sudoers_template.yaml.j2"
        dest: "/etc/sudoers.d/allow_apt_{{ item.name }}.yaml"
        owner: root
        group: root
        mode: '0400'
      loop: "{{ user.user }}"
      become: true
      when: item.can_update | bool
