# use python as image

# add an "author" label

# install the following packages with pip3: flask, redis, requests, uwsgi

# create work dir /app

# copy the cmd-script (cmd.sh) into the image

# copy the app folder (./app) into the image

# Expose the ports 9090 9091

# Start the cmd-script
