---

- name: 01-solution-ping
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping the host
      ansible.builtin.ping:
      register: answer

    - name: Print the outcome
      ansible.builtin.debug:
        var: answer
