# Specify base image "docker/whalesay:latest" (FROM)

# Install apt package "fortunes" "apt-get update --quiet && apt-get install -y fortunes fortune-mod" (RUN)

# Specify start command "/usr/games/fortune | cowsay" (CMD, use shell form since we use the pipe operator)
